# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='StundenLetzerMonat',
            field=models.IntegerField(null=True),
        ),
    ]
