# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeiterfassung',
            name='ueberhang',
            field=models.FloatField(null=True),
        ),
    ]
