# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_myuser_stundenletzermonat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='StundenLetzerMonat',
            field=models.DateTimeField(null=True),
        ),
    ]
