# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_zeiterfassung_pause'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zeiterfassung',
            name='Ueberhang',
        ),
        migrations.RemoveField(
            model_name='zeiterfassung',
            name='pause',
        ),
    ]
