# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_zeiterfassung_ueberhang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zeiterfassung',
            name='ueberhang',
        ),
    ]
