# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_zeiterfassung_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeiterfassung',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
