# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20160620_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='StundenLetzerMonat',
            new_name='StundenLetzterMonat',
        ),
    ]
