# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20160630_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Initstunden',
            field=models.IntegerField(null=True),
        ),
    ]
