# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_zeiterfassung_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='betreuer',
            name='vorname',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='zeiterfassung',
            name='betreuer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Betreuer'),
        ),
        migrations.AlterField(
            model_name='betreuer',
            name='nachname',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
