# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_zeiterfassung_ueberhang'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Ueberhang',
            field=models.FloatField(default=10.0),
        ),
    ]
