# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_myuser_initstunden'),
        ('login', '0004_auto_20160912_1523'),
    ]

    operations = [
    ]
