# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20160620_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='StundenLetzterMonat',
            field=models.FloatField(null=True),
        ),
    ]
