# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundenkonto', '0003_auto_20160614_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vertragsuebersicht',
            name='Ueberhang',
        ),
    ]
