# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenkonto', '0004_remove_vertragsuebersicht_ueberhang'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusUebersicht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monatsstunden', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='VertragsUebersicht',
        ),
    ]
