# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenkonto', '0006_statusuebersicht_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusuebersicht',
            name='Ueberhang',
            field=models.FloatField(default=0),
        ),
    ]
