# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenkonto', '0007_statusuebersicht_ueberhang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusuebersicht',
            name='Monatsstunden',
            field=models.FloatField(default=0),
        ),
    ]
