# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenkonto', '0008_auto_20160630_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusuebersicht',
            name='Monat',
            field=models.IntegerField(default=7),
        ),
    ]
