# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundenkonto', '0009_statusuebersicht_monat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusuebersicht',
            name='Monat',
            field=models.IntegerField(),
        ),
    ]
