# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundenkonto', '0011_studenten'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenten',
            old_name='user',
            new_name='User',
        ),
    ]
