# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stundenkonto', '0012_auto_20161219_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenten',
            name='monate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stundenkonto.StatusUebersicht'),
        ),
    ]
