# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundenkonto', '0013_studenten_monate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenten',
            name='monate',
        ),
    ]
